title: "Database from scratch"
tagline: "Пишем database на Go"
description: "Пишем полноценную базу данных на Go с нуля"
url: "https://edylcrm.github.io"
baseurl: "/db-from-scratch"

author: "edylcrm"
github_username: edylcrm

theme: minima

lang: ru-RU

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
