title: "Database from scratch"
tagline: "Пишем database на Go"
description: "Серия статей о том, как устроены LSM-деревья, и полная реализация на Go"
url: "https://edylcrm.github.io"
baseurl: "/db-from-scratch"

remote_theme: cotes2020/jekyll-theme-chirpy

lang: ru-RU

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
